spring:
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /jpa

---
spring:
  profiles: dev
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: primaryData
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #默认使用下划线命名风格，这里可以改成驼峰式命名


# 日志
logging:
  level:
    com.example.jpademo: DEBUG